# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer\EnterYear.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Year(object):
    def setupUi(self, Year):
        Year.setObjectName("Year")
        Year.resize(292, 267)
        self.gridLayoutWidget = QtWidgets.QWidget(Year)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 291, 271))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.YearSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.YearSpinBox.setMinimum(2000)
        self.YearSpinBox.setMaximum(2050)
        self.YearSpinBox.setObjectName("YearSpinBox")
        self.gridLayout.addWidget(self.YearSpinBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ReportButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ReportButton.setObjectName("ReportButton")
        self.gridLayout.addWidget(self.ReportButton, 1, 0, 1, 2)

        self.retranslateUi(Year)
        QtCore.QMetaObject.connectSlotsByName(Year)

    def retranslateUi(self, Year):
        _translate = QtCore.QCoreApplication.translate
        Year.setWindowTitle(_translate("Year", "Form"))
        self.label.setText(_translate("Year", "Введите год"))
        self.ReportButton.setText(_translate("Year", "Получить отчет"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Year = QtWidgets.QWidget()
    ui = Ui_Year()
    ui.setupUi(Year)
    Year.show()
    sys.exit(app.exec_())
