# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer\OrderWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderWindow(object):
    def setupUi(self, OrderWindow):
        OrderWindow.setObjectName("OrderWindow")
        OrderWindow.resize(721, 667)
        self.gridLayoutWidget = QtWidgets.QWidget(OrderWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 721, 671))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.DepartureComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.DepartureComboBox.setObjectName("DepartureComboBox")
        self.gridLayout.addWidget(self.DepartureComboBox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.ArrivalComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.ArrivalComboBox.setObjectName("ArrivalComboBox")
        self.gridLayout.addWidget(self.ArrivalComboBox, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.CargoTypeComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.CargoTypeComboBox.setObjectName("CargoTypeComboBox")
        self.gridLayout.addWidget(self.CargoTypeComboBox, 4, 1, 1, 1)
        self.CustomerEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.CustomerEdit.setObjectName("CustomerEdit")
        self.gridLayout.addWidget(self.CustomerEdit, 1, 1, 1, 1)
        self.CargoComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.CargoComboBox.setObjectName("CargoComboBox")
        self.gridLayout.addWidget(self.CargoComboBox, 5, 1, 1, 1)
        self.OrderDateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.OrderDateEdit.setObjectName("OrderDateEdit")
        self.gridLayout.addWidget(self.OrderDateEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.WeightSpinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.WeightSpinBox.setMaximum(100000000)
        self.WeightSpinBox.setObjectName("WeightSpinBox")
        self.gridLayout.addWidget(self.WeightSpinBox, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.OrderButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.OrderButton.setObjectName("OrderButton")
        self.gridLayout.addWidget(self.OrderButton, 7, 0, 1, 2)

        self.retranslateUi(OrderWindow)
        QtCore.QMetaObject.connectSlotsByName(OrderWindow)
        OrderWindow.setTabOrder(self.OrderDateEdit, self.CustomerEdit)
        OrderWindow.setTabOrder(self.CustomerEdit, self.DepartureComboBox)
        OrderWindow.setTabOrder(self.DepartureComboBox, self.ArrivalComboBox)
        OrderWindow.setTabOrder(self.ArrivalComboBox, self.CargoTypeComboBox)
        OrderWindow.setTabOrder(self.CargoTypeComboBox, self.CargoComboBox)
        OrderWindow.setTabOrder(self.CargoComboBox, self.WeightSpinBox)

    def retranslateUi(self, OrderWindow):
        _translate = QtCore.QCoreApplication.translate
        OrderWindow.setWindowTitle(_translate("OrderWindow", "Form"))
        self.label_6.setText(_translate("OrderWindow", "Куда нужно привезти?"))
        self.label_2.setText(_translate("OrderWindow", "Груз"))
        self.label_3.setText(_translate("OrderWindow", "Суммарный вес груза"))
        self.label_7.setText(_translate("OrderWindow", "Заказчик"))
        self.label_5.setText(_translate("OrderWindow", "Откуда нужно отвезти?"))
        self.label.setText(_translate("OrderWindow", "Тип груза"))
        self.label_4.setText(_translate("OrderWindow", "Дата заказа"))
        self.OrderButton.setText(_translate("OrderWindow", "Оформить заказ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrderWindow = QtWidgets.QWidget()
    ui = Ui_OrderWindow()
    ui.setupUi(OrderWindow)
    OrderWindow.show()
    sys.exit(app.exec_())
