# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Designer\SellTruckWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SellTruckWindow(object):
    def setupUi(self, SellTruckWindow):
        SellTruckWindow.setObjectName("SellTruckWindow")
        SellTruckWindow.resize(683, 663)
        self.gridLayoutWidget = QtWidgets.QWidget(SellTruckWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 30, 621, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.CustomerEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.CustomerEdit.setObjectName("CustomerEdit")
        self.gridLayout.addWidget(self.CustomerEdit, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.TruckIdComboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.TruckIdComboBox.setObjectName("TruckIdComboBox")
        self.gridLayout.addWidget(self.TruckIdComboBox, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.SellDateEdit = QtWidgets.QDateEdit(self.gridLayoutWidget)
        self.SellDateEdit.setObjectName("SellDateEdit")
        self.gridLayout.addWidget(self.SellDateEdit, 3, 1, 1, 1)
        self.SellButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.SellButton.setObjectName("SellButton")
        self.gridLayout.addWidget(self.SellButton, 4, 0, 1, 2)

        self.retranslateUi(SellTruckWindow)
        QtCore.QMetaObject.connectSlotsByName(SellTruckWindow)

    def retranslateUi(self, SellTruckWindow):
        _translate = QtCore.QCoreApplication.translate
        SellTruckWindow.setWindowTitle(_translate("SellTruckWindow", "Form"))
        self.label_5.setText(_translate("SellTruckWindow", "Дата"))
        self.label_3.setText(_translate("SellTruckWindow", "Покупатель"))
        self.label_4.setText(_translate("SellTruckWindow", "ID грузовика"))
        self.SellButton.setText(_translate("SellTruckWindow", "Продать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SellTruckWindow = QtWidgets.QWidget()
    ui = Ui_SellTruckWindow()
    ui.setupUi(SellTruckWindow)
    SellTruckWindow.show()
    sys.exit(app.exec_())
